services:
  game-server:
    image: ghcr.io/flow-industries/flow-game:latest
    ports:
      - "7000:7000/udp"
    environment:
      REGION: eu
      MAX_PLAYERS: 100
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    environment:
      WATCHTOWER_POLL_INTERVAL: 5
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
    restart: always
