---
all:
  hosts:
    flow-1:
      ansible_host: flow-1.flow.industries
      stacks: [site, auth, talk]
      domains:
        - { host: "flow.industries", upstream: "site:3000", zone: "flow.industries" }
        - { host: "id.flow.industries", upstream: "auth:3000", zone: "flow.industries" }
        - { host: "flow.talk", upstream: "talk:3000", zone: "flow.talk" }
    game-1:
      ansible_host: game-1.flow.industries
      stacks: [game-server, game-web]
      game_region: eu
      game_port: 9999
      game_max_players: 100
      firewall_additional_rules:
        - "iptables -A INPUT -p tcp --dport {{ game_port }} -j ACCEPT"
      domains:
        - { host: "flow.game", upstream: "game-web:80", zone: "flow.game" }
        - { host: "eu.play.flow.game", zone: "flow.game", proxied: false }
