---
- name: Setup servers
  ansible.builtin.import_playbook: setup.yml
- name: Deploy stacks
  ansible.builtin.import_playbook: deploy.yml
- name: Configure DNS
  ansible.builtin.import_playbook: dns.yml
