use anyhow::{Result, bail};
use serde::Deserialize;
use serde_json::{Value, json};

use crate::config::{Chart, Fleet};

const ORG: &str = "default";
const FOLDER: &str = "default";
const TITLE: &str = "Flow Overview";
const GRID_WIDTH: i64 = 192;
const DEFAULT_HEIGHT: i64 = 28;
const DEFAULT_WIDTH: i64 = 96;

fn panel_width(spec: Option<&str>) -> i64 {
    match spec {
        Some("full") => 192,
        Some("third") => 64,
        Some("quarter") => 48,
        _ => DEFAULT_WIDTH,
    }
}

fn build_panel(id: i64, chart: &Chart, x: i64, y: i64, w: i64) -> Value {
    let mut fields = json!({
        "stream": chart.stream,
        "stream_type": "logs",
        "x": [{"label": chart.x, "alias": chart.x, "column": chart.x}],
        "y": [{"label": chart.y, "alias": chart.y, "column": chart.y}],
        "filter": {"filterType": "group", "logicalOperator": "AND", "conditions": []}
    });
    if let Some(b) = &chart.breakdown {
        fields["breakdown"] = json!([{"label": b, "alias": b, "column": b}]);
    }
    json!({
        "id": format!("panel-{id}"),
        "type": chart.chart_type,
        "title": chart.title,
        "description": "",
        "config": {"show_legends": true},
        "queryType": "sql",
        "queries": [{
            "query": chart.sql.trim(),
            "customQuery": true,
            "fields": fields,
            "config": {"promql_legend": ""}
        }],
        "layout": {"x": x, "y": y, "w": w, "h": DEFAULT_HEIGHT, "i": id}
    })
}

fn build_tab(tab_id: &str, name: &str, charts: &[&Chart], next_id: &mut i64) -> Value {
    let mut panels = Vec::new();
    let mut row_x = 0i64;
    let mut row_y = 0i64;
    for c in charts {
        let w = panel_width(c.width.as_deref());
        if row_x + w > GRID_WIDTH {
            row_x = 0;
            row_y += DEFAULT_HEIGHT;
        }
        panels.push(build_panel(*next_id, c, row_x, row_y, w));
        row_x += w;
        *next_id += 1;
    }
    json!({"tabId": tab_id, "name": name, "panels": panels})
}

pub fn build_dashboard(fleet: &Fleet) -> Option<Value> {
    let mut tabs = Vec::new();
    let mut next_id = 1i64;

    if !fleet.charts.is_empty() {
        let charts: Vec<&Chart> = fleet.charts.iter().collect();
        tabs.push(build_tab("fleet", "Fleet", &charts, &mut next_id));
    }

    let mut app_names: Vec<&String> = fleet.apps.keys().collect();
    app_names.sort();
    for app_name in app_names {
        let app = &fleet.apps[app_name];
        if app.charts.is_empty() {
            continue;
        }
        let charts: Vec<&Chart> = app.charts.iter().collect();
        tabs.push(build_tab(app_name, app_name, &charts, &mut next_id));
    }

    if tabs.is_empty() {
        return None;
    }

    Some(json!({
        "title": TITLE,
        "description": "Auto-generated by iron",
        "tabs": tabs,
    }))
}

#[derive(Deserialize)]
struct DashboardInner {
    #[serde(rename = "dashboardId")]
    dashboard_id: Option<String>,
    title: Option<String>,
}

#[derive(Deserialize)]
struct DashboardSummary {
    v8: Option<DashboardInner>,
}

#[derive(Deserialize)]
struct DashboardList {
    dashboards: Vec<DashboardSummary>,
}

pub async fn sync(
    client: &reqwest::Client,
    base: &str,
    user: &str,
    password: &str,
    fleet: &Fleet,
) -> Result<()> {
    let Some(body) = build_dashboard(fleet) else {
        return Ok(());
    };

    let list: DashboardList = client
        .get(format!("{base}/api/{ORG}/dashboards?folder={FOLDER}"))
        .basic_auth(user, Some(password))
        .send()
        .await?
        .json()
        .await?;

    let existing_id = list
        .dashboards
        .into_iter()
        .filter_map(|d| d.v8)
        .find(|d| d.title.as_deref() == Some(TITLE))
        .and_then(|d| d.dashboard_id);

    let resp = if let Some(id) = existing_id {
        let cur: Value = client
            .get(format!("{base}/api/{ORG}/dashboards/{id}"))
            .basic_auth(user, Some(password))
            .send()
            .await?
            .json()
            .await?;
        let hash = cur.get("hash").and_then(Value::as_str).unwrap_or("");
        client
            .put(format!(
                "{base}/api/{ORG}/dashboards/{id}?folder={FOLDER}&hash={hash}"
            ))
            .basic_auth(user, Some(password))
            .json(&body)
            .send()
            .await?
    } else {
        client
            .post(format!("{base}/api/{ORG}/dashboards?folder={FOLDER}"))
            .basic_auth(user, Some(password))
            .json(&body)
            .send()
            .await?
    };

    if !resp.status().is_success() {
        let s = resp.status();
        let t = resp.text().await.unwrap_or_default();
        bail!("dashboard sync: {s} {t}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn chart(title: &str, width: Option<&str>) -> Chart {
        Chart {
            title: title.into(),
            chart_type: "bar".into(),
            stream: "_rumdata".into(),
            x: "t".into(),
            y: "n".into(),
            sql: "SELECT 1 AS t, 1 AS n".into(),
            width: width.map(ToString::to_string),
            breakdown: None,
        }
    }

    #[test]
    fn panel_width_defaults_to_half() {
        assert_eq!(panel_width(None), 96);
        assert_eq!(panel_width(Some("half")), 96);
        assert_eq!(panel_width(Some("full")), 192);
        assert_eq!(panel_width(Some("third")), 64);
        assert_eq!(panel_width(Some("quarter")), 48);
        assert_eq!(panel_width(Some("bogus")), 96);
    }

    #[test]
    fn layout_wraps_at_grid_width() {
        let charts = vec![chart("a", None), chart("b", None), chart("c", None)];
        let refs: Vec<&Chart> = charts.iter().collect();
        let mut id = 1;
        let tab = build_tab("t", "T", &refs, &mut id);
        let panels = tab.get("panels").unwrap().as_array().unwrap();
        assert_eq!(panels.len(), 3);
        assert_eq!(panels[0]["layout"]["x"], 0);
        assert_eq!(panels[0]["layout"]["y"], 0);
        assert_eq!(panels[1]["layout"]["x"], 96);
        assert_eq!(panels[1]["layout"]["y"], 0);
        assert_eq!(panels[2]["layout"]["x"], 0);
        assert_eq!(panels[2]["layout"]["y"], 28);
    }

    #[test]
    fn full_width_panel_takes_full_row() {
        let charts = vec![chart("a", Some("full")), chart("b", None)];
        let refs: Vec<&Chart> = charts.iter().collect();
        let mut id = 1;
        let tab = build_tab("t", "T", &refs, &mut id);
        let panels = tab.get("panels").unwrap().as_array().unwrap();
        assert_eq!(panels[0]["layout"]["w"], 192);
        assert_eq!(panels[1]["layout"]["x"], 0);
        assert_eq!(panels[1]["layout"]["y"], 28);
    }

    #[test]
    fn empty_returns_none() {
        use std::collections::HashMap;
        let fleet = Fleet {
            domain: None,
            network: "flow".into(),
            servers: HashMap::new(),
            apps: HashMap::new(),
            runners: HashMap::new(),
            secrets: Default::default(),
            webhook: None,
            charts: Vec::new(),
        };
        assert!(build_dashboard(&fleet).is_none());
    }
}
